### ISSUE TITLE
[FEATURE] Add caching-layer

### ISSUE THREAD

**Issue by neufeind** [gumlet/php-image-resize#102]
It might be helpful to be able to give the library a source-image, some resizing and just request to get a temp-filepath back. The caching-layer could then determine if for the given source-image (timestamp+size? optionally some user-provided source-hash?) and with the given resize-configuration (as well as file-format, quality-setting, ...) the image has already been processed (there is a matching temp-file) or if it needs to create one and return that instead.
If you change the source-image or the image-processing (resize-options, ...) a new temp-file would be generated.

**Comment by neufeind** [comment]
Quick demo: https://gist.github.com/neufeind/9dc00796ff01935debab78bff6deffaf
$resize = new \SpeedPartner\ImageResizeCached('demo.jpg');
$resize->resizeToBestFit(200,200);
echo $resize->getProcessedFilepath('imagecache');
The image-loading is defered. Of course then you can't catch errors during loading the image during construct() anymore, but the fileinfo-call would have returned an error already.

**Comment by adityapatadia** [comment]
It's too complicated to add in this library and I feel it's little outside its scope. I am also not sure how big the benefit would be.
