### ISSUE TITLE
Feature Request : Animated Gifs.

### ISSUE THREAD

**Issue by andreas83** [gumlet/php-image-resize#105]
is there any way to resize aniamted gifs?

**Comment by adityapatadia** [comment]
The base library PHP-GD which is used by this library does not support animated GIFs. If you would like to add, there are other libraries which support it. Please create PR.

**Comment by peter279k** [comment]
Unfortunately, if we want to use the GD extension to support the gif extension file, we have to specify the GD extension version. Please see more details about the official [doc](http://php.net/manual/en/function.imagegif.php#refsect1-function.imagegif-notes).
