### ISSUE TITLE
Add additional parameter to "resizeToBestFit" that allows to return an image with exact size, requested in parameters.

### ISSUE THREAD

**Issue by glebavladimir** [gumlet/php-image-resize#106]
Now, when I call the "resizeToBestFit" method it creates an image with the same ratio but different size. Sometimes you need this, but the other time, you get into the cases where you need in return an image that has exact width and height you've put into the parameters. The image shouldn't be scaled, but the rest of it should be filled with transparent\blanc\given color.

Ex.:
`public function resizeToBestFit($max_width, $max_height, $allow_enlarge = false, $fill_color = false){}`

**Comment by adityapatadia** [comment]
Closing this.

**Comment by adityapatadia** [comment]
Let me open it. If you can find a solution, please point and if you can create PR, it would be great.

**Comment by felipetnh** [comment]
I managed to do it by changing the save() function.
I send an extra param that has the exact size of the picture I want.
If that param is not null, I create and image with that exact size, then I center the image and then save it.

I can post the code here, if you want. But I'm pretty sure someone can make a better code than me. I had no time to do it, so it doesn't really look pretty... haha

**Comment by felipetnh** [comment]
I can never proper style those blocks of code.
Can you edit and proper style it?

**Comment by peter279k** [comment]
Hi @felipetnh. If possible, can you send the PR for this?

And we can review this code snippet :).

**Comment by felipetnh** [comment]
PR created.
