### ISSUE TITLE
Undefined function Gumlet\finfo_open() 

### ISSUE THREAD

**Issue by IamAlta** [gumlet/php-image-resize#107]
PHP Fatal error:  Call to undefined function Gumlet\finfo_open() in /mydirtofile/ImageResize.php on line 109.

Now what?

**Comment by peter279k** [comment]
Hi, can you provide the current PHP enivronment?I never get this error.
Thanks.

**Comment by IamAlta** [comment]
Let me know what else you might need. Meanwhile, I programmed my own resize and crop routine. But, since you responded like a firefighter (fast with interest :) ), here it is.

Linux System | Linux van-vps-1074-1.ezp.net 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64
Build Date | Feb 28 2018 19:13:41

PHP Version 5.5.38

Fileinfo installed

GD installed
GD Support | enabled
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.3.11
T1Lib Support | enabled
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 6b
PNG Support | enabled
libPNG Version | 1.2.49
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30411
XBM Support | enabled
WebP Support | enabled

**Comment by adityapatadia** [comment]
@peter279k any idea why many people face this?

**Comment by peter279k** [comment]
It looks strange because the PHP 5.5 in Travis build is passed successfully.
And I also run the sample code and it's worked successfully.
Here is my sample code:

```
require 'vendor/autoload.php';
$image = new ImageResize('image.jpg');
$image->scale(50);
$image->save('image2.jpg')
```
Can you provide the sample code? Thanks.

**Comment by peter279k** [comment]
I just provide the dummy and sample repo [here](https://github.com/peter279k/image_resize).

**Comment by peter279k** [comment]
I also doubt that the ```fileinfo``` extension is not installed correctly in your PHP environment....
Can you run the ```php -m | grep fileinfo``` and comment that output result?

Thanks.

**Comment by IamAlta** [comment]
$ php -m | grep fileinfo
fileinfo

**Comment by peter279k** [comment]
@IamAlta, can you provide your problematic code?

Thanks.

**Comment by IamAlta** [comment]
I appreciate your diligence on this, but I programmed my own and removed yours. Sorry. I hope you track this down, you seem to be interested in remedying it.

**Comment by peter279k** [comment]
Actually, the official package does not have this problem because it can be passed by the Travis build.
And your code is problematic.

That's why I want to check out your code :+1: .

**Comment by peter279k** [comment]
Sure! I will notify you next month.

**Comment by adityapatadia** [comment]
@IamAlta I understood that you have resolved your problem but we just need to make sure that this library works well for everyone. Please let us know as you get time so we can fix any potential problem. @peter279k thanks a lot for your continued support.

**Comment by kimeli** [comment]
I had the same issue and solved it by enabling fileinfo

**Comment by IamAlta** [comment]
It was the missing line in php.ini, extension=fileinfo.so
Techs said it was installed, they didn't go as far to check it was active in php.ini.
You guys are great!

**Comment by jeorlie** [comment]
Hi,  I know this is old but I experience this too today. Here is the sample code.


```
$image = new Gumlet\ImageResize($_FILES['mainphoto']['tmp_name']);

  if($_FILES['mainphoto']['size'] > 800000) // 800kb
  {
    // lets resize it
    $image->scale(70);
    $image->save($dest);
  }
  else
  {
    $image->save($dest);
  }
```

the funny thing is that it works on my other ajax script. I'm now confused. Other script is working while other one won't I get the error 

`Call to undefined function Gumlet\finfo_open()`

**Comment by jeorlie** [comment]
Following must be enabled if using windows.
php_gd2.dll
php_fileinfo.dll
