### ISSUE TITLE
Resolution changed while saving an imagefrom server to local directory

### ISSUE THREAD

**Issue by OmisBrown** [gumlet/php-image-resize#110]
I used the save() method to save an image in my directory but when I checked the resolution it has changed from 300 ppp to 72 ppp, did I missed something or there is an issue ?

**Comment by peter279k** [comment]
What's code that you run?
Can you show the sample code?

Thanks.

**Comment by OmisBrown** [comment]
$Width = 500;
$Height = 500;
$new_image = 'C:\Users\ultrapc\Downloads\Unamed.jpeg'
$image = new ImageResize($new);
$image->crop($Width, $Height, true,ImageResize::CROPCENTER);
$image->save('C:/Users/App/ImageCropped/new_image'  , $image->source_type);

**Comment by peter279k** [comment]
I run your code and use the sample jpeg image file which is in the ```./test/ressources``` folder.
The original and cropped image are the same resolution after running your provided code.
Here is my sample code:

```
<?php

require 'vendor/autoload.php';

use Gumlet\ImageResize;

$width = 500;
$height = 500;
$original = './test/ressources/test_xmp.jpg';

$image = new ImageResize($original);

$image->crop($width, $height, true, ImageResize::CROPCENTER);
$image->save('./test_xmp_cropped.jpg', $image->source_type);

```

**Comment by OmisBrown** [comment]
Did you test with a 300 dpi resolution image ?

**Comment by peter279k** [comment]
Mm...It looks strange.
When I use the ```300x300``` image file to crop the new image.
The cropped image resolution is ```96x96```.

I will take a look at this.

**Comment by OmisBrown** [comment]
This is my main problem, please let me know if you found the answer for it. I got stuck for 2 days without any solutions !

**Comment by adityapatadia** [comment]
Closing this. We will reopen if many people face this.
