### ISSUE TITLE
CROPCENTER not cropping center

### ISSUE THREAD

**Issue by IamAlta** [gumlet/php-image-resize#111]
Unless I misunderstand your instructions, it seems that 
    $image->resizeToBestFit($width, $height, ImageResize::CROPCENTER);
is not cropping to center and adding black background to part of the image.

    $image = new ImageResize(image.jpg);
    $image->quality_jpg = $quality;
    $image->resizeToBestFit($width, $height, ImageResize::CROPCENTER);
    $image->save(new_image.jpg);

RESULT:
![gumlet-sample](https://user-images.githubusercontent.com/34579958/39876491-8c9f81d4-5430-11e8-99e9-8d9a761bed14.jpg)

Same result with

    $image = new ImageResize('image.jpg');
    $image->resizeToLongSide(500);
    $image->save('image2.jpg');
    $image = new ImageResize('image.jpg');
    $image->resizeToShortSide(300);
    $image->save('image2.jpg');

Do you have a function that will do what we need?
Thank you!

**Comment by IamAlta** [comment]
@peter279k,
Anyone working on the issues? We are about to go live and wonder if this is fixable.
Thank you. I appreciate the good work that you do.

**Comment by peter279k** [comment]
Hi @IamAlta, thank you for your reply.
Can you provide the sample image? And I can test this and make the proper cropping  image approach.

Thanks.

**Comment by IamAlta** [comment]
@peter279k,
See my first comment, above.

**Comment by peter279k** [comment]
@IamAlta, do you have the "original" image?
Thanks.

**Comment by peter279k** [comment]
@IamAlta, it seems that you use the wrong way to cropt the image.
Please use the following code to crop image.

```
<?php

require_once 'vendor/autoload.php';

use Gumlet\ImageResize;
use Gumlet\ImageResizeException;

// The file
$filename = 'bird.png';

$image = new ImageResize($filename);
$image->crop(100, 150)->save('cropped.png');

```
It's worked for me.

Thanks.

**Comment by IamAlta** [comment]
That worked. Thank you. 
I appreciate your work :)
