### ISSUE TITLE
scaling affects the color of image

### ISSUE THREAD

**Issue by simplyniceweb** [gumlet/php-image-resize#116]
![download 1](https://user-images.githubusercontent.com/5621415/41850403-ff5dc49c-78b6-11e8-8373-33fb5fcb8dfe.jpg)
![download](https://user-images.githubusercontent.com/5621415/41850404-ffc38138-78b6-11e8-9f27-9551837742a8.jpg)

that's 50% scaling, any idea why? or how to keep the image original color?

**Comment by adityapatadia** [comment]
http://php.net/manual/en/function.imagegammacorrect.php It can be related to gamma correction. Can you check further on that?

**Comment by adityapatadia** [comment]
This is fixed in `1.9.1`. Thanks for reporting.

**Comment by veloso11** [comment]
I have the same problem, using 1.9.3 :

![6282160](https://user-images.githubusercontent.com/20184741/75055628-4d4ad480-54cd-11ea-9b31-20e48fd27704.jpg)
![6282160](https://user-images.githubusercontent.com/20184741/75055628-4d4ad480-54cd-11ea-9b31-20e48fd27704.jpg)

**Comment by veloso11** [comment]
![Uploading 6282160_.jpg…]()
![6282160](https://user-images.githubusercontent.com/20184741/75055689-6a7fa300-54cd-11ea-9a0a-fd27ea364bc0.jpg)

**Comment by veloso11** [comment]
![6282160_](https://user-images.githubusercontent.com/20184741/75055746-82572700-54cd-11ea-9d3d-a139d12c9f90.jpg)
![6282160](https://user-images.githubusercontent.com/20184741/75055761-85eaae00-54cd-11ea-928b-66150ae079bc.jpg)
I have the same problem using version 1.9.3
