### ISSUE TITLE
Colour loss in blurred images

### ISSUE THREAD

**Issue by mintymatt** [gumlet/php-image-resize#120]
When freecropping and then saving graduated JPEG images, I notice that some of the colours are being stripped out? I looks like it's quality related, but I've reset the values.

```
$imageResizer = new \Gumlet\ImageResize($source);
$imageResizer->freecrop($crop_settings->width, $crop_settings->height, $crop_settings->x, $crop_settings->y);
$imageResizer->quality_jpg = 100;
$imageResizer->quality_png = 0;
$imageResizer->interlace = 0;
$imageResizer->save($destination);
```

Input Image:

![image](https://user-images.githubusercontent.com/30320791/44578216-f9054e00-a78a-11e8-8220-756d6dae0998.png)

Output Image:

![image](https://user-images.githubusercontent.com/30320791/44578222-fd316b80-a78a-11e8-81da-41516a1e3d8e.png)

**Comment by adityapatadia** [comment]
It can be either due to chroma subsampling or ICC profile issue. Please check if you find something on those lines.

**Comment by adityapatadia** [comment]
Also, please use latest version of this library as it has fix for gamma correction issue which can affect colors a lot.

**Comment by mintymatt** [comment]
_Using version 1.9.1 (currently the latest version)._

Looks like it is a **colour profile issue** - this specific image has en embedded `sRGB` colour profile.

![image](https://user-images.githubusercontent.com/30320791/44580686-c9f2da80-a792-11e8-9254-468540f81a76.png)

I might start looking into detecting and chaning colour profiles before sending through gumlet, though I'm unsure if this is necessary or effecient. I'm also unsure which colour profile I shold be aiming for.

What would you suggest? 

Thank-you for your help

**Comment by adityapatadia** [comment]
sRGB is best for displaying images on the web.

**Comment by valentindragan** [comment]
This thing is happening to me too. The thread has been closed though no solutions has been provided.

```
    $image = new ImageResize('uploads/hibiscus-1520217326.jpg');
    $image->save('uploads/hibiscus-1520217326-2.jpg');
```

![hibiscus-1520217326-2](https://user-images.githubusercontent.com/4279613/70235633-fc4bff80-176b-11ea-9bbb-c08c6d36a7c4.jpg)
![hibiscus-1520217326](https://user-images.githubusercontent.com/4279613/70235634-fce49600-176b-11ea-9dd3-51e5c9b3cfb5.jpg)

**Comment by AbbesBendaoud10** [comment]
@valentindragan  did you find a solution ?
