### ISSUE TITLE
Resize Image Down, Huge Increase In Image Size

### ISSUE THREAD

**Issue by bsmartclick** [gumlet/php-image-resize#121]
Hi,

I am trying to use your class for resize, but when i try the resize method in a specific image which is 160kb and [2394x2394] - i try to resize to 2000x2000 - i get an image with size about 1.8mb and after waiting about 42 seconds. iam resize to a smaller size why iam get size too large with respect to the original image. image is png extension, when i the jpg extension with size 232kb it convert to 829kb but with less time then the png (about 11.5 seconds).

is there any way to avoid this large size and time & make it always smaller size if i am resizing to smaller dimensions?

i attached the png version if want to make some test.

Thanks,
![a](https://user-images.githubusercontent.com/43085360/45251482-a497cc00-b34f-11e8-8315-a446d3a2068d.png)

**Comment by jonutz** [comment]
I encounter the same problem when i try to save:

`$image = new ImageResize('image.jpg');
$image->save('image2.jpg', null, 100);
`

If the original image has 20 KB then the resulting image2 has 34-40 KB (varies).

**Comment by peter279k** [comment]
I think the `GD` resizing image excludes the reducing file image size.
It also can refer this [post](https://stackoverflow.com/questions/20300304/php-resizing-image-increase-image-size).

If want to keep the reducing image file, I think it should use `imagejpeg` or `imagepng` to reduce/compress the image file size after resizing image file completely 👍.
It can check this related post [here](https://stackoverflow.com/questions/11418594/which-is-the-best-php-method-to-reduce-the-image-size-without-losing-quality).

**Comment by peter279k** [comment]
@adityapatadia, perhaps this work is out of range. I think using the image optimizer tool to optimize /compress images is the proper way.

**Comment by adityapatadia** [comment]
I also feel the same. Some images are compressed with certain tools in a better way. We can't implement image compression tools in this repo. We will close this for now.

**Comment by peter279k** [comment]
@bsmartclick, if you want to optimize/compress image, please check this [image optimization tool](https://github.com/spatie/image-optimizer).

You can use this tool to do optimization/compression after resizing the images :).
