### ISSUE TITLE
Resizing image error

### ISSUE THREAD

**Issue by isatybaldyev13** [gumlet/php-image-resize#124]
I am trying to resize image , here is my code :
$image = new ImageResize($imageDir);

        $sizes = [
            's' => 20,
            'm' => 150,
            'l' => 300,
            'xl' => 600,
        ];

        foreach ($sizes as $key=>$size) {
            $image->resize($size, $size,$allow_enlarge = True);
            $image->save($imageDirectory.'/'.$key.'/'.$fileName);
        }
,
but it is not resized correctly , it saved with black filter 
![7u2eqtxmetbfit4hxu2bqtvrkdwdzyjb](https://user-images.githubusercontent.com/18219034/46088316-d95fac00-c1b4-11e8-9d9a-c20846b525bf.jpeg)

original one is 
![7u2eqtxmetbfit4hxu2bqtvrkdwdzyjb](https://user-images.githubusercontent.com/18219034/46088379-f72d1100-c1b4-11e8-958d-126ebf40a741.jpeg)

requirements : 
Composer version 1.7.2
PHP 7.2.10
"gumlet/php-image-resize": "1.9.1"

**Comment by peter279k** [comment]
@isatybaldyev13, thank you for your reply.
The `1.9.1` has the same problem after I use your code.

And the `mater` branch has been solved this problem. You can check that if possible :+1:.

Here is my sample code I test:

```php
<?php

require_once 'vendor/autoload.php';

use Gumlet\ImageResize;
use Gumlet\ImageResizeException;

// The file
$filename = 'image.jpeg';

$image = new ImageResize($filename);

$sizes = [
    's' => 20,
    'm' => 150,
    'l' => 300,
    'xl' => 600,
];

foreach ($sizes as $key => $size) {
    $image->resize($size, $size,$allow_enlarge = true);
    $image->save('image' . $key . '.jpeg');
}

```

**Comment by peter279k** [comment]
@isatybaldyev13. Sorry. It's my fault.

The master branch still has the same problem. After tracing the source code. I found that the `imagegammacorrect` has been added in this [commit](https://github.com/gumlet/php-image-resize/commit/d36a7bcd679445ec8f310fdbecac5d40b0c587de).

It's worked fine when I removed the related `imagegammacorrect` function.
I think this functions will cause this problem.

@adityapatadia, please take a look at that. Thanks.

**Comment by felipetnh** [comment]
I had to remove the `imagegammacorrect` as well in order to work.

**Comment by adityapatadia** [comment]
Gamma correction can now be disabled as of ```v1.9.2```.
https://github.com/gumlet/php-image-resize#gamma-color-correction
