### ISSUE TITLE
Library is breaking when finfo_open is not available

### ISSUE THREAD

**Issue by sfatfarma** [gumlet/php-image-resize#127]
Hello,

Nice library, congrats. 

Please add this check for finfo_open, in case it is not available:

`
        if(!function_exists('finfo_open'))
        {
            throw new ImageResizeException('finfo_open does not exist, cannot resize image.');
        }
`

Regards.

**Comment by sfatfarma** [comment]
I use PHP 7.0. What do you mean by PR?

**Comment by adityapatadia** [comment]
Pull request.

**Comment by peter279k** [comment]
Well, this issue can be closed because the `fileinfo` extension has already defined in [composer.json](https://github.com/gumlet/php-image-resize/blob/master/composer.json).
