### ISSUE TITLE
 How to output() correctly?

### ISSUE THREAD

**Issue by mike0liveira** [gumlet/php-image-resize#131]
**This works:**

```
<?php

include 'ImageResize.php';
include 'ImageResizeException.php';

$image = new \Gumlet\ImageResize('img/test.jpg');

$image->resizeToWidth(170);
$image->output();

?>
```

**This does not:**

```
<?php

include 'ImageResize.php';
include 'ImageResizeException.php';

$image = new \Gumlet\ImageResize('img/test.jpg');

$image->resizeToWidth(170);

?>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, world!</title>
  </head>
  <body>
  	<img src="<?php $image->output()?>"> or just <?php $image->output()?>
  </body>
</html>
```

The screen just gets black...

**Comment by peter279k** [comment]
@mike0liveira, thank you for your reply.

Can you provide the `php-image-resize` version?

Thanks.

**Comment by peter279k** [comment]
@mike0liveira, can you provide the sample image that you use?

Thanks.

**Comment by mike0liveira** [comment]
Just a regular wallpaper from windows, but i tested with others imgs, like personal pics, always the same...

from the first code:
![image](https://user-images.githubusercontent.com/33181091/49326108-d625cb00-f52b-11e8-9261-0d641d641763.png)

second one, with the html code:
![image](https://user-images.githubusercontent.com/33181091/49326155-872c6580-f52c-11e8-9b55-e6e75dea41ed.png)

**Comment by mike0liveira** [comment]
![test](https://user-images.githubusercontent.com/33181091/49326173-dbcfe080-f52c-11e8-9ebb-2ba0ba148df8.jpg)

**Comment by peter279k** [comment]
@mike0liveira, thank you for your reply.

The `$image->output()` will output the image binary and the `src` should set the image path, not image binary.

If you want to present the image, please use the `base64_encode` to encode binary firstly.

Try this:
```php
include 'ImageResize.php';
include 'ImageResizeException.php';

$image = new \Gumlet\ImageResize('img/test.jpg');

$image->resizeToWidth(170);

// The file
$filename = 'test.jpg';
$image = new ImageResize($filename);
$image->resizeToWidth(70);
$binary = $image->output();

echo '<img src=data:image/jpeg;"' . base64_encode($binary) . '">';

```

Thanks.

**Comment by mike0liveira** [comment]
not work, the image is rendered before hits the echo...

**Comment by mike0liveira** [comment]
dont work, the img is rendered before hits the echo...

**Comment by peter279k** [comment]
@mike0liveira, I've updated the sample code, please try again.

It's worked fine for me.

**Comment by Droeftoeter** [comment]
You need to use `->getImageAsString()` if you want to capture the result in a string.

**Comment by peter279k** [comment]
Try this code:

```php
<?php

include 'ImageResize.php';
include 'ImageResizeException.php';

$image = new \Gumlet\ImageResize('img/test.jpg');

$image->resizeToWidth(170);

?>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, world!</title>
  </head>
  <body>
  	<img src="<?php 'data:image/jpeg;' . base64_encode($image->output()) ?>">
  </body>
</html>

```

**Comment by mike0liveira** [comment]
well i guess u are confuse...

thats is what happen:
![image](https://user-images.githubusercontent.com/33181091/49326581-fa38da80-f532-11e8-89fc-2ec73b2594ea.png)

![image](https://user-images.githubusercontent.com/33181091/49326589-189ed600-f533-11e8-9685-ac193646a2c2.png)

**Comment by peter279k** [comment]
@Droeftoeter, thank you for your reply.

Actually it's not worked fine and presents the blank page.

My latest sample code worked fine for me :).

**Comment by peter279k** [comment]
@mike0liveira, your sample code is wrong.....You have the unused `echo` in `img` tag.

Please refer my latest sample code again.

**Comment by mike0liveira** [comment]
exactly as yours
![image](https://user-images.githubusercontent.com/33181091/49326688-ba72f280-f534-11e8-917c-fe4e84f798a6.png)

the same
![image](https://user-images.githubusercontent.com/33181091/49326698-e8583700-f534-11e8-9aa4-2ca7b701de6d.png)

**Comment by peter279k** [comment]
@Droeftoeter, after checking your latest sample code, it presents the image binary directly on page.

@mike0liveira, do you want this approach?

**Comment by Droeftoeter** [comment]
@peter279k I've fixed the sample code in my comment.

If you want to show the resized image on a page you have 3 options:

* Store the image in a publically accessable file and refer to that inside the `<img>`-tag (`<img src="/filename.jpg />`)
* Use the `->getImageAsString()` to capture the output in a string, then base64_encode that and create a [Data URI](https://css-tricks.com/data-uris/) and use that as the `src`-value. (`<img src="(data:image/jpeg;base64,ENCODED_DATA_HERE" />`)
* Make the `src` refer to another PHP file which will `->output()` the image. (`<img src="anotherfile.php" />`)

**Comment by peter279k** [comment]
@Droeftoeter, exactly that approach is good enough!

**Comment by peter279k** [comment]
@Droeftoeter, your latest sample code still output the image binary directly on web page...

**Comment by mike0liveira** [comment]
**SOLUTION:**

> Make the src refer to another PHP file which will ->output() the image. (img src=anotherfile.php)

**imgoutput.php**
```
<?php

include 'ImageResize.php';
include 'ImageResizeException.php';

$image = new \Gumlet\ImageResize($_GET['imgid']);

$image->resizeToWidth(170);
$image->output();

?>
```

**yourhtmlpage.php**
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, world!</title>
  </head>
  <body>
       <img src="imgoutput.php?imgid=PATH_AND_NAME_IMAGE">
  </body>
</html>
```

TY U ALL, whe have a resize on the fly...

**Comment by peter279k** [comment]
I glad you've solved your problem :).

**Comment by adityapatadia** [comment]
I missed discussions on thread but nice to see it was resolved. Checkout https://www.gumlet.com if you want to resize image on the fly. It's very cheap service and you would also help fund development of this library.
