### ISSUE TITLE
restore gamma correction after save

### ISSUE THREAD

**Issue by razvanioan** [gumlet/php-image-resize#134]
At the end of `save()` method, the gamma correction should be restored on source_image.
In case if further save calls on the same image / object, those will get darker with each save.

Simple fix:
```php
imagedestroy($dest_image);

// restore gamma correction on source_image
if ($this->gamma_correct) {
  imagegammacorrect($this->source_image, 1.0, 2.2);
}

return $this;
```

**Comment by adityapatadia** [comment]
It's closed in #132
