### ISSUE TITLE
"Unsupported file type" for webp extension

### ISSUE THREAD

**Issue by walangkaji** [gumlet/php-image-resize#135]
Hi, I try with webp extension for image, but i find a error like this:

```PHP Fatal error:  Uncaught exception 'Gumlet\ImageResizeException' with message 'Unsupported file type' in H:\test\imageResize\vendor\gumlet\php-image-resize\lib\ImageResize.php:114
Stack trace:
#0 H:\test\imageResize\test.php(5): Gumlet\ImageResize->__construct('1.webp')
#1 {main}
  thrown in H:\test\imageResize\vendor\gumlet\php-image-resize\lib\ImageResize.php on line 114

Fatal error: Uncaught exception 'Gumlet\ImageResizeException' with message 'Unsupported file type' in H:\test\imageResize\vendor\gumlet\php-image-resize\lib\ImageResize.php:114
Stack trace:
#0 H:\test\imageResize\test.php(5): Gumlet\ImageResize->__construct('1.webp')
#1 {main}
  thrown in H:\test\imageResize\vendor\gumlet\php-image-resize\lib\ImageResize.php on line 114
```
my code:
```
require 'vendor/autoload.php';
use \Gumlet\ImageResize;

$image = new ImageResize('1.webp');

var_dump($image);
```

I try to find a some information, and this I got:
```
$finfo = finfo_open(FILEINFO_MIME_TYPE);
$info  = finfo_file($finfo, '1.webp');
```

> and the result is: "application/octet-stream"

while in the repository just detect contain "image", with the repo code:
```
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        if (strstr(finfo_file($finfo, $filename), 'image') === false) {
            throw new ImageResizeException('Unsupported file type');
        }
```
is this a mistake?

anyone know whats wrong?
I use windows 10,
PHP 5.6.36 (cli) (built: Apr 25 2018 16:45:32)
Source Image: https://www.gstatic.com/webp/gallery/1.webp
php-image-resize version: 1.9.*

**Comment by peter279k** [comment]
It looks like the `webp` image format cannot be recognized by the `finfo` extension.

But it looks strange.

I use the `php-7.0+` version to use the following code and the result is `image/webp`.

```php
$finfo = finfo_open(FILEINFO_MIME_TYPE);
finfo_file($finfo, '1.webp');
```
After using the same code on `php-5.6` version, I get the MIME type result is `application/octet-stream`.

I think you should run the `php-7.0+` version to avoid this recognized problem.

**Comment by walangkaji** [comment]
@peter279k didn't any solution for php 5.6?
I'm not ready to use php 7+ hehehe....

but, thanks for suggestion peter.

**Comment by peter279k** [comment]
@walangkaji, thank you for your reply.

Actually, I don't think it has the current way to detect the `webp` image format on `php-5.6` version.

I think It has the hard-core way to solve this issue.

We should use the `file_get_contents` to read file and detect the binary strings exist the `WEBPVP8` string.

If existing these strings, this file should be the `webp` image format.

**Comment by walangkaji** [comment]
@peter279k Hi peter,
Yap, I think php 5.x not supported to read webp, only work with 7+.

thanks for your suggestion.
it's awesome.

**Comment by adityapatadia** [comment]
Closing this. Please let us know if any further help is needed.

**Comment by peter279k** [comment]
@adityapatadia, the further help is about recognizing the `webp` image format on `php-5.5` and `php-5.6` version.

I think we can create another issue about this :).

**Comment by MarioRadu** [comment]
Hi, i'm using "gumlet/php-image-resize": "^1.9" and PHP version : 7.3.2 and I'm getting the same error "Unsupported file type".

I'm using  the createFromString method : 

$image = ImageResize::createFromString(base64_decode($base64Picture));
 The output from finfo_file($finfo, $filename) at line 112 from ImageResize.php class is : 

"application/octet-stream" which should contain image but it doesn't so it throws a new ImageResizeException. 
What can I do ? Thanks ! :)

**Comment by peter279k** [comment]
> Hi, i'm using "**gumlet/php-image-resize": "^1.9**" and PHP version : **7.3.2** and I'm getting the same error "**Unsupported file type**".
> 
> I'm using the **createFromString** method :
> 
> **$image = ImageResize::createFromString(base64_decode($base64Picture));**
> The output from **finfo_file($finfo, $filename)** at line 112 from ImageResize.php class is :
> 
> "**application/octet-stream**" which should contain image but it doesn't so it throws a new ImageResizeException.
> What can I do ? Thanks ! :)

This issue and related PR is not merged and concerned so it will not be any latest version to resolve this issue.
