### ISSUE TITLE
Recognize WEBP image format on `php-5.x` version

### ISSUE THREAD

**Issue by peter279k** [gumlet/php-image-resize#136]
Actually, this package still requires the `php-5.5` and `php-5.6` versions.

And it should find the way to be compatible with `php-5.5` and `php-5.6` versions.

Please take look at the detailed comments on issue #135.

If we drop the `php-5.x` versions, this issue will be resolved.

**Comment by phaberest** [comment]
I would suggest to leave this version in a separate branch to let who still uses php 5.x use it and eventually keep working on fixes. I know it is silly, but sadly there are still a lot of platforms that are stuck to it.

At least we can move on.

**Comment by peter279k** [comment]
@phaberest, thank you for your reply.

I agree with you that we create the separate branch to support the `php-5.x` and `php-7.x` version.

@adityapatadia, please look at this and suggest the recommendations.

Thanks.

**Comment by adityapatadia** [comment]
I think it makes sense to create different branch. I still have doubts about Packagist though. How do we work there? Do we keep 1.x version for PHP 5.x and 2.x version for PHP 7.x?

**Comment by peter279k** [comment]
@adityapatadia, thank you for your concern.

Actually, it's fine to do that you mention.

The [Guzzle](https://github.com/guzzle/guzzle#version-guidance) package also use the different releases.

**Comment by adityapatadia** [comment]
I have checked some docs and found that WebP image is supported in PHP 5.x.

http://php.net/manual/en/function.imagecreatefromwebp.php

http://php.net/manual/en/function.imagewebp.php

Can we work with these functions?

**Comment by adityapatadia** [comment]
We already have support for these functions in library. The only blocker is finfo_open function I think.

**Comment by peter279k** [comment]
@adityapatadia, that's right.

The only blocker is about using the `finfo_open` function to detect the `webp` image.

It only reads the image contents to detect the format is `webp` on supporting `php-5.x`.

**Comment by adityapatadia** [comment]
I think we should solve it without using any different versions. It would be easy to maintain.

**Comment by peter279k** [comment]
@adityapatadia, maybe we have to use the `version_compare` to detect PHP versions.

If the PHP version is `5.x`, it will use the `file_get_contetns` to determine the `webp` image format.

And the PHP version is `7.x`, it uses the `finfo_open` to check the `webp` image format.

What do you think about that?

**Comment by adityapatadia** [comment]
@peter279k works fine. I think we can go ahead with this.

**Comment by adityapatadia** [comment]
@peter279k would it be possible for you to create a PR?

**Comment by peter279k** [comment]
Hi @adityapatadia, just assign me to notify me to work on this issue.
