### ISSUE TITLE
Convert from PNG to JPG - or any format

### ISSUE THREAD

**Issue by jenstornell** [gumlet/php-image-resize#139]
```php
$image = new ImageResize('image.png');
$image->convert('jpg');
$image->crop(200, 200);
$image->save('image2.jpg');
```

An alternative to the above would be to check if the input extension is different from the output extension and then force a convert in those cases.

**Comment by peter279k** [comment]
@jenstornell, thank you for your reply.

It sounds like a good idea. What do you think about this, @adityapatadia.

BTW, according to the sample  code, the `$image->convert('jpg'));` has the additional `)`.

It should enhance the sample code :).

**Comment by jenstornell** [comment]
I made a repo a while ago with just this functionality. Maybe it can be helpful.

https://github.com/kirby-deprecated-plugins/superthumbs/blob/master/thumb.php#L76

```php
function pngtojpg($filePath, $output, $quality) {
        $image = imagecreatefrompng($filePath);
        $bg = imagecreatetruecolor(imagesx($image), imagesy($image));
        imagefill($bg, 0, 0, imagecolorallocate($bg, 255, 255, 255));
        imagealphablending($bg, TRUE);
        imagecopy($bg, $image, 0, 0, 0, 0, imagesx($image), imagesy($image));
        imagedestroy($image);
        $result = imagejpeg($bg, $output, $quality);
        imagedestroy($bg);
        return $result;
      }
```

**Comment by peter279k** [comment]
Hi @jenstornell, thank you for your code snippets.

I appreciate your help.

And I also figure out how about other approaches about image conversion?

I think it's not only `PNG` to `JPG` conversion, but it also has the `JPG` to `PNG` conversion and so on.

I'm not sure whether this feature is out of range on this repository.

Perhaps we need to do another image library for image conversions :).

**Comment by jenstornell** [comment]
@peter279k I agree. There are more cases than just PNG > JPG.

I've searched for just a conversion library between different formats. I found nothing. In all the searches there was libraries similar to this repo where you can convert between formats but also crop, resize etc.

I still think it could be interesting to have a repo that handles just the conversions of different image formats.

**Pros:**

- Will be separated so you can mix and match libraries.
- If only a conversion library is needed, you will get just that. No bloat.
- Performance will be better with less code.
- Probably easier to maintain when it's more isolated.
- There are no libraries like it, at least not what I've found.

**Cons:**

- May be more work to add two files instead of one.
- The code for the user may be longer because two classes will be used. Two step process.
- Do it need to save the file to disc two times? One for the conversion and one for the crop?

No matter what approach, I've found one interesting repo:
https://github.com/rakibtg/PHP-ImageToWebp (untested).

The code of it is really beautiful:
https://github.com/rakibtg/PHP-ImageToWebp/blob/master/ImageToWebp.php It does however only convert to webp.

It's possible with PHP to convert to other formats as well: https://www.php.net/manual/en/function.imagepng.php

**Comment by jenstornell** [comment]
@peter279k I had some time over to create a converter. I think it's already really good.

https://github.com/jenstornell/php-image-converter

**Comment by peter279k** [comment]
@jenstornell. Thank you for your concern.

And I will review them at my available time :).

**Comment by adityapatadia** [comment]
I think it would be great to merge this conversion feature with this library. @jenstornell would it be possible for you to create a PR?

**Comment by qant** [comment]
You can save from .png to .jpg like thi: `$image->save(str_replace('.png', '.jpg', $resized_image_name),IMAGETYPE_JPEG);`

**Comment by adityapatadia** [comment]
This can be achieved with this code:

```php
$image = new ImageResize('image.png');
$image->crop(200, 200);
$image->save('image2.jpg',IMAGETYPE_JPEG);
```
