### ISSUE TITLE
The Travis CI build will be failed because of undefined imagecreatefromwebp function

### ISSUE THREAD

**Issue by peter279k** [gumlet/php-image-resize#143]
@adityapatadia, I've noticed that the `imagecreatefromwebp` function will be undefined in Travis CI build.

And it also effects issue #136.

I also create related discussion on Travis CI community, but it seems that nobody reply on this [discussion thread](https://travis-ci.community/t/how-to-enable-webp-image-format-support-in-php-7/3209).

I also try possible solution for this issue on this [test Travis CI build](https://travis-ci.org/peter279k/php-travis-gd/builds/544302712).

I also find that it can use `root` user to build the PHP environment with supporting `webp` function, but this will not support `php-5.5` test.

What do you think about this?

**Comment by adityapatadia** [comment]
May be we should drop 5.5 test.

**Comment by adityapatadia** [comment]
@peter279k I think Travis will never fix it but with help of new Github actions, we can easily fix this one.

**Comment by peter279k** [comment]
> @peter279k I think Travis will never fix it but with help of new Github actions, we can easily fix this one.

@adityapatadia, thanks for your reply. Yes. I agree that we can migrate Travis CI to GitHub Action.

I will close this PR and create another PR to let Travis CI migrate to GitHub Action.

**Comment by adityapatadia** [comment]
I have migrated.
