### ISSUE TITLE
Poor jpeg output quality if gamma correction is enabled

### ISSUE THREAD

**Issue by sksksksk** [gumlet/php-image-resize#146]
I had some quality issues on certain jpeg images scaled with php-image-resize. Even with a quality setting of 100, part of the images showed ugly artifacts.

I found that disabling gamma correction restores the image to an acceptable quality. I do not know what gamma correction exactly is supposed to do, so can't comment on whether changing the parameters of the gamma correction would result in better images.

Here is the code I used for testing. The original image is named orig.jpg. It produces 3 scaled down images (from 2000px width to 1600px width). For 3 quality settings (80,90,100). Once with gamma correction enabled and once without. So a total of 6 images are produced.

```
$destination_width = 1600;
foreach([true,false] as $gamma) {
	foreach([80,90,100] as $quality) {
		$image = new \Gumlet\ImageResize(__DIR__.'/orig.jpg');
		$image->quality_jpg = $quality;
		$image->gamma($gamma);
		$image->resizeToWidth($destination_width, false);
		$destination = __DIR__.'/'.$quality.'_'.($gamma?'gammatrue':'gammafalse').'.jpg';
		$image->save($destination);
	}
}
```

Here is the original image.
![orig](https://user-images.githubusercontent.com/3510901/67392043-7eaba600-f5a8-11e9-953f-f6d3506b31f1.jpg)

For the quality 90 scaled down image, here is the result with gamma correction enabled. Notice the artifacts on the floor **(you may need to view the image in a new tab for the full size)**
![90_gammatrue](https://user-images.githubusercontent.com/3510901/67392070-8b2ffe80-f5a8-11e9-9a4e-93b845dfa15b.jpg)

For the quality 90 scaled down image, here is the result without gamma correction. The artifacts are gone
![90_gammafalse](https://user-images.githubusercontent.com/3510901/67392120-a6027300-f5a8-11e9-9e2a-bc6bf0e91f3b.jpg)

So the question is: is there some setting I am missing that would allow to use gamma correction without having these quality issues?

**Comment by adityapatadia** [comment]
You should disable Gamma correction if you are facing such issues.
