### ISSUE TITLE
Thumbia based on gumlet/php-image-resize

### ISSUE THREAD

**Issue by jenstornell** [gumlet/php-image-resize#147]
https://github.com/jenstornell/thumbia

**Problem**

A problem I have with all libraries like this is that they are using paths. I often have a HTML string containing images with urls.

**Solution**

With my library, you send a string of HTML containing images and it will make thumbnails of the images. Then it will replace the urls with the new thumbnail urls.

**Comment by gronostajo** [comment]
It's unclear what kind of action you're expecting. Do you want _gumlet/php-image-resize_ to include this feature too? It doesn't look like a good fit for the library in its current form.

**Comment by jenstornell** [comment]
@gronostajo I removed it.
