### ISSUE TITLE
Resize image from URL

### ISSUE THREAD

**Issue by Machou** [gumlet/php-image-resize#149]
Hello

It's possible to resize an image from url ?

**Comment by peter279k** [comment]
At this moment, this feature is not available on this package.

You need to download the image file or contents then using this package to do image resizing :).

**Comment by peter279k** [comment]
The image URL is responsible for another PHP package (Such as HTTP client) and it's out of range for this PHP package.

If having any further problem/request, please reopen this issue. And this issue is going to be closed :).
