### ISSUE TITLE
EXIF Orientation problem

### ISSUE THREAD

**Issue by jeffreydodds** [gumlet/php-image-resize#152]
Not sure if it's a PHP version issue but I had to change line 186 from:

        $orientation = $exif['Orientation'];
to

        $orientation = $exif['IFD0']['Orientation'];

This got the auto-rotation working for me.

PHP EXIF info:
EXIF Version | 7.2.24-0ubuntu0.18.04.3
Supported EXIF Version | 0220

**Comment by peter279k** [comment]
This is the feature about `exif_read_data` function.

It will be `$exif['Orientation']` or `$exif['IFD0']['Orientation']` probably when reading the image with orientated tag.

For example, reading following image with `exif_read_data('./Portrait_0.jpg')` and I get following result:

And the JPG image is available [here](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_0.jpg).

```
[
     "FileName" => "Portrait_0.jpg",
     "FileDateTime" => 1596194366,
     "FileSize" => 248531,
     "FileType" => 2,
     "MimeType" => "image/jpeg",
     "SectionsFound" => "ANY_TAG, IFD0",
     "COMPUTED" => [
       "html" => "width="1200" height="1800"",
       "Height" => 1800,
       "Width" => 1200,
       "IsColor" => 1,
       "ByteOrderMotorola" => 1,
     ],
     "Orientation" => 0,
     "XResolution" => "72/1",
     "YResolution" => "72/1",
     "ResolutionUnit" => 2,
     "YCbCrPositioning" => 1,
   ]

```

Maybe we can check whether `$exif['Orientation'];` or `$exif['IFD0']['Orientation'];` to try to get the orientated tag :100:

**Comment by migo315** [comment]
Have the same problem. Should I create a PR?

**Comment by peter279k** [comment]
> 
> 
> Have the same problem. Should I create a PR?

Thanks for your reply. You can create this PR :).

**Comment by migo315** [comment]
I was just about to work on this problem, but I realised that my error has a different cause.
