### ISSUE TITLE
Set internal error state after any chained operation

### ISSUE THREAD

**Issue by KarelWintersky** [gumlet/php-image-resize#153]
something like
```
$image
  ->resizeToBestFit(100, 100))
   ->save('1.jpg', IMAGETYPE_JPEG);

var_dump($image->errorState);
```

**Comment by peter279k** [comment]
Do you have any suggestion about setting error state?

It seems that we have to define/customize error states.

**Comment by KarelWintersky** [comment]
I'll think about it...

**Comment by KarelWintersky** [comment]
just more unmasked exceptions required. Making fork... pls, wait :)
