### ISSUE TITLE
"undefined function Gumlet\imagejpeg()"

### ISSUE THREAD

**Issue by OzanSimsekler** [gumlet/php-image-resize#154]
`Message: Call to undefined function Gumlet\imagejpeg()`

I'm getting this error while using the library and I think this is a host-related issue, likely some extension being disabled or so. Could you help me with figuring out the issue so that I can contact my host and have them perform the necessary changes?

Using PHP 7.4.4 on shared hosting.

**Comment by peter279k** [comment]
Do your `GD` extension loaded successfully on `php-7.4` version?

**Comment by OzanSimsekler** [comment]
@peter279k Yup, both `GD ` and `fileinfo` appears to have been enabled and loaded.

**Comment by peter279k** [comment]
Could you use `var_dump(gd_info())` to print reult on your shared hosting?

**Comment by OzanSimsekler** [comment]
There you go:

`array(14) { ["GD Version"]=> string(26) "bundled (2.1.0 compatible)" ["FreeType Support"]=> bool(true) ["FreeType Linkage"]=> string(13) "with freetype" ["GIF Read Support"]=> bool(true) ["GIF Create Support"]=> bool(true) ["JPEG Support"]=> bool(false) ["PNG Support"]=> bool(true) ["WBMP Support"]=> bool(true) ["XPM Support"]=> bool(false) ["XBM Support"]=> bool(true) ["WebP Support"]=> bool(false) ["BMP Support"]=> bool(true) ["TGA Read Support"]=> bool(true) ["JIS-mapped Japanese Font Support"]=> bool(false) }`

And I really appreciate the help!

**Comment by peter279k** [comment]
According to the result you write, the problematic support is as follows:

```
......
 ["JPEG Support"]=> bool(false)
......
```

It seems that your `GD` extension doesn't have JPEG support.

That's the reason why `imagejpeg` function is undefined.

The expected output should be as follows via `gd_info` function:

```
 gd_info()
[
     "GD Version" => "2.2.5",
     "FreeType Support" => true,
     "FreeType Linkage" => "with freetype",
     "GIF Read Support" => true,
     "GIF Create Support" => true,
     "JPEG Support" => true,
     "PNG Support" => true,
     "WBMP Support" => true,
     "XPM Support" => true,
     "XBM Support" => true,
     "WebP Support" => true,
     "BMP Support" => true,
     "TGA Read Support" => true,
     "JIS-mapped Japanese Font Support" => false,
   ]
```

The ` "JPEG Support"`  should be `true`.

**Comment by OzanSimsekler** [comment]
Ah, that makes perfect sense! Is this something I can resolve by editing the php.ini or .htaccess file, or should I contact the hosting support? I don't have control over the extension otherwise since it's shares hosting.

**Comment by OzanSimsekler** [comment]
Did some digging and apparently PHP 7.3 has the JPEG Support _true_ by default, so I went back to it from 7.4 and it worked! No idea why it was _false_ in 7.4. Thanks a lot for helping with identifying the issue!

**Comment by peter279k** [comment]
If you want to use `php-7.4` on that shared hosting, you have to contact the hosting support.

And let them help you to enable `JPEG` support on `php-7.4` version.
