### ISSUE TITLE
resize is adding a black and white background

### ISSUE THREAD

**Issue by AbbesBendaoud10** [gumlet/php-image-resize#155]
Hello , im using image reisze to resize images, it's working properly in my local , but in production, the resize is adding a black and white backgrounds on resized images.

Any solution ?

**Comment by peter279k** [comment]
I'm not sure what the differences for your production and local development environment...

It doesn't make sense about it's worked on local development and not worked on production.

**Comment by AbbesBendaoud10** [comment]
Hi @peter279k  maybe it's the quality of the image which is decreased

**Comment by peter279k** [comment]
This issue should be reproduced, I'm not sure where current problem is...

**Comment by onexoff** [comment]
hello same issue here @AbbesBendaoud10  have you found the solution

**Comment by AbbesBendaoud10** [comment]
@onexoff nooo not yet

**Comment by kadogithub** [comment]
I changed the gamma correction to false and it worked!

Version 2.0 // line 27 public $gamma_correct = false;

**Comment by peter279k** [comment]
> I changed the gamma correction to false and it worked!
> 
> Version 2.0 // line 27 public $gamma_correct = false;

You can also use `gamma` method to determine `$gamma_correct` is enabled or disabled.

**Comment by peter279k** [comment]
It seems to be fixed and this issue is going to be closed at this moment.

If still having the similar question, please write the comment :).
