### ISSUE TITLE
Incorrect phpdoc typing

### ISSUE THREAD

**Issue by gronostajo** [gumlet/php-image-resize#158]
The method `save` takes an `$image_type` argument, which according to its phpdoc accepts a string. However the code expects it to be one of `IMAGETYPE_*` constants, which are integers. This causes static analyzers like PHPStan or Psalm to flag correct usage as erroneous. The fix is to simply update the phpdoc.

**Comment by adityapatadia** [comment]
Please create PR. Happy to merge.
