### ISSUE TITLE
Can't rezise image stored in a string.

### ISSUE THREAD

**Issue by someguyincali** [gumlet/php-image-resize#160]
I have a PNG stored in a string taken from mysql BLOB. I do not want the image on the servers file system due to plan on using AES_ENCRYPT/DECRYPT to protect the image (user signature).
I get the following error:
Warning: is_file() expects parameter 1 to be a valid path, string given in /var/www/html/signature/ImageResize.php on line 108

**Comment by peter279k** [comment]
If possible, could you provide your sample code?

I can try to reproduce your issue and find where the problem is.

**Comment by peter279k** [comment]
It seems to be a feature because the `ImageResize` class constructor supports `file name`, not image binary string at this moment.

**Comment by KarelWintersky** [comment]
I think, you can use something like this:
```
'data://image/png;base64,' . base64_encode($blob_data); 
```
as resource filename

**Comment by KarelWintersky** [comment]
```
$str = file_get_contents(__DIR__ . '/test_in.jpg'); // get data from file or BLOB
$str = 'data://image/jpeg;base64,' . base64_encode( $str ); // also, you will store mime type of your image near BLOB data

$image = new \Gumlet\ImageResize($str);
$image->scale(50)->save('test_out.png', IMAGETYPE_PNG);
```
