### ISSUE TITLE
Add bitmap (bmp) support

### ISSUE THREAD

**Issue by KarelWintersky** [gumlet/php-image-resize#164]
subj.

See https://www.php.net/manual/ru/function.imagecreatefrombmp.php 
https://stackoverflow.com/questions/16557822/imagecreatefrombmp-not-working-on-php

**Comment by peter279k** [comment]
It seems that the `imagecreatefrombmp` function will be available on `php-7.2` version at least.

It should implement `imagecreatefrombmp` function before `php-7.2` version if we want to resolve this issue.

**Comment by KarelWintersky** [comment]
set feature request mark.
