### ISSUE TITLE
imageistruecolor false positive resulting in big filesizes

### ISSUE THREAD

**Issue by AlbertMN** [gumlet/php-image-resize#166]
As decribed in issue #63, when resizing a non-truecolor image to a truecolor image, it can result in significantly bigger filesizes. The pull request #65 adding the `quality_truecolor` parameter was supposed to fix this, but the line that determines whether the new image should be truecolor or not is; `if (!$this->quality_truecolor && !imageistruecolor($this->source_image))`, and in my case `imageistruecolor(...)` always seem to return `true`. Simply replacing `&&` with `||` fixed this for me, and I suggest this be set in the code as well, as I can't think of a case where you after having set `quality_truecolor` to false would want to possibly end up with a truecolor image anyways.

I can create a PR if need be, but I figured as it's simply replacing two characters it might be easier to just create an issue.

**Comment by peter279k** [comment]
It looks great and please go ahead with that :).

**Comment by AlbertMN** [comment]
@peter279k PR #167 created.

**Comment by KarelWintersky** [comment]
Is tests passed for small and big files?

**Comment by peter279k** [comment]
Yes. It should be good to add the file to be tested on `tests` folder.
