### ISSUE TITLE
Chaining doesn't seem to retain original image

### ISSUE THREAD

**Issue by G2G2G2G** [gumlet/php-image-resize#170]
Code doesn't really matter since the example in the readme does the same thing, but you can see it produces an extremely dark version, other than making it really dark it seems to have the rest of the quality intact.. 
(does this with all images) 

```
        $image = ImageResize::createFromString(base64_decode($image_data_base64));
        $image->crop(200, 200)
        ->save($destination . $time . '_s.jpg', IMAGETYPE_JPEG)
        ->resizeToLongSide(1300)
        ->save($destination . $time . '_b.jpg', IMAGETYPE_JPEG);
```

![1](https://user-images.githubusercontent.com/50514477/112076511-8cbc7800-8b48-11eb-994d-1a9c719744e8.jpg)

not using chaining at all produces fine images.

**Comment by peter279k** [comment]
It seems to be same as PR #163.

I try to organize the for `v2` and still wait for @adityapatadia reponse.

**Comment by KarelWintersky** [comment]
@G2G2G2G , maintainers of `gumlet/php-image-resize` rejected any changes or pull requests from me about V2 (see closed PR)

You can use my package: `ajur-media/php-image-resize`

**Comment by peter279k** [comment]
Sorry. I'm busy at the recent time. And I need to figure out the current way to integrate your PR #163.

Sorry for my delay response.

**Comment by KarelWintersky** [comment]
Average ONE YEAR, LOL....

**Comment by adityapatadia** [comment]
I am still ready to accept smaller PR to get this fixed.

**Comment by KarelWintersky** [comment]
https://github.com/gumlet/php-image-resize/pull/163

You delayed the process of reviewing my code for so long, and then made so many ridiculous and meaningless demands (by refusing to provide the linter configuration or a document about YOUR codestyle), that I lost all desire to help you fix errors in YOUR library.

You couldn't find time for more than two months to review changes that clearly improved the performance of your code and fixed many problems.

After that you made a lot of ridiculous claims about my work: “extra lines”, “extra spaces”, and so on and so forth.

Sorry, but I don't feel like investing in your library anymore. I corrected all the mistakes that you made during its development and released my own based on your code according to the license you specified.

You can use my code in your projects.
