### ISSUE TITLE
Gamma Correct , image bad color

### ISSUE THREAD

**Issue by falconsw** [gumlet/php-image-resize#171]
when trying to upload images of different sizes, a black layer was formed in picture colors other than the original size. this problem ;

public $gamma_correct = false;

I figured it out by typing.

![Ekran görüntüsü 2021-04-25 103900](https://user-images.githubusercontent.com/6252528/115985017-8475b380-a5b2-11eb-9b31-7379a225fd75.png)
![Ekran görüntüsü 2021-04-25 103951](https://user-images.githubusercontent.com/6252528/115985035-a2dbaf00-a5b2-11eb-80af-99c4b4d5ef5d.png)
![Ekran görüntüsü 2021-04-25 104013](https://user-images.githubusercontent.com/6252528/115985036-a40cdc00-a5b2-11eb-9652-4b2c943b56f1.png)

**Comment by peter279k** [comment]
I think it's related to PR #163 and I consider creating the `2.x` branch to resolve that or using alternative approach to resolve existed codes.

**Comment by KarelWintersky** [comment]
@falconsw , maintainers of `gumlet/php-image-resize` rejected any changes or pull requests from me about V2 (see closed PR)

You can use my package: `ajur-media/php-image-resize`

**Comment by peter279k** [comment]
Sorry. I'm busy at the recent time. And I need to figure out the current way to integrate your PR #163.

Sorry for my delay response.

**Comment by adityapatadia** [comment]
We are now disabling default gamma correction now.
