### ISSUE TITLE
PHP 8.1 Deprecation warnings for float to int conversions

### ISSUE THREAD

**Issue by madhancock** [gumlet/php-image-resize#174]
Using version 2.0.0
PHP Version 8.1.0

The following deprecation warnings are triggered:

```
Deprecated: Implicit conversion from float 177.09977827050997 to int loses precision in ImageResize.php on line 283
Deprecated: Implicit conversion from float 177.09977827050997 to int loses precision in ImageResize.php on line 323
```

**Comment by madhancock** [comment]
@peter279k I've seen you've been relatively active on this project. Any word as to the state of it? Looks like there have been completed PR's since the last release 18 months ago but the release cycle itself isn't happening.

The reason I ask is my team could help resolve some of the issues but there's little point if releases are no longer being made to packagist. Do you know if this project is still "alive"?

**Comment by peter279k** [comment]
I think it's alive probably. Actually, I have limited permissions on this project.

I can merge and review PR, but I cannot release the version.

Maybe we can ping @adityapatadia to let me have the permission about releasing versions :).

**Comment by haidarvm** [comment]
Yes, please help. I need it to run with php 8.1

**Comment by madhancock** [comment]
Sounds like we're waiting on word from @adityapatadia with regards to having some additional permissions for @peter279k or an alternative plan.

**Comment by adityapatadia** [comment]
Hey, I am pretty much happy to merge PR and release new version. Please ping me once we are ready to go.

**Comment by adityapatadia** [comment]
Version 2.0.1 should fix it.

**Comment by bmpf** [comment]
The error is still there : 
```
Deprecated: Implicit conversion from float 274.5 to int loses precision in /var/www/html/public/img/vendor/gumlet/php-image-resize/lib/ImageResize.php on line 357

```

**Comment by adityapatadia** [comment]
Can you create PR? It should be simple one.

—
Regards,
Aditya Patadia
