### ISSUE TITLE
imagecreatetruecolor and  imagecopyresampled warning error: implicit float to int conversion

### ISSUE THREAD

**Issue by cybrobin** [gumlet/php-image-resize#182]
imagecreatetruecolor and  imagecopyresampled warning error: implicit float to int conversion

**Comment by peter279k** [comment]
Could you reproduce the issue?

Do you use the [latest version](https://github.com/gumlet/php-image-resize/releases/tag/2.0.2) to get the issue?

**Comment by adityapatadia** [comment]
Latest version is known to fix it. Please comment if otherwise.
