### ISSUE TITLE
imageFlip() function removed in v2.0.1 but still referenced in Readme.

### ISSUE THREAD

**Issue by jarofgreen** [gumlet/php-image-resize#185]
https://github.com/gumlet/php-image-resize/compare/2.0.0...2.0.1

But it's still in readme: https://github.com/gumlet/php-image-resize#flip

It's also still in the API docs linked from the readme: https://gumlet.github.io/php-image-resize/class-Gumlet.ImageResize.html

Is it the intention that this function should still be supported / available?

**Comment by jarofgreen** [comment]
For others, here's a workaround for PHP 5.5 and up:

                $image->addFilter(function ($image) {
                    imageflip($image, IMG_FLIP_HORIZONTAL);
                });

**Comment by adityapatadia** [comment]
Readme updated.
