### ISSUE TITLE
how to fix fatal eror ?

### ISSUE THREAD

**Issue by rozblog1388** [gumlet/php-image-resize#191]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Gumlet\ImageResize::__construct(), 0 passed in /home/test/public_html/test.php on line 7 and exactly 1 expected in /home/test/public_html/include/plugin/resize/ImageResize.php:103 Stack trace: #0 /home/rozup/public_html/test.php(7): Gumlet\ImageResize->__construct() #1 {main} thrown in /home/test/public_html/include/plugin/resize/ImageResize.php on line 103

**Comment by sutrus** [comment]
Constructor requires one parameter
There are many examples in README.md
