### ISSUE TITLE
imagecreatefrompng(): gd-png: libpng warning

### ISSUE THREAD

**Issue by asv1979** [gumlet/php-image-resize#192]
Hello, i got such error.
"gumlet/php-image-resize": "2.0.1"
"php": "^7.4"

use Gumlet\ImageResize;

$image->quality_png = $this->qualityImagePng;

$image = new ImageResize($imagePath);
$image->resizeToWidth(1280);
$image->resizeToHeight(1280);
$image->save($this->imagePath);

imagecreatefrompng(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image
vendor/gumlet/php-image-resize/lib/ImageResize.php line 155

**Comment by adityapatadia** [comment]
I think it's due to a bug in libpng library. Can you update to latest library and check?
Reference: http://sourceforge.net/p/libpng/bugs/165/
