### ISSUE TITLE
malformed method signature for crop() in docs

### ISSUE THREAD

**Issue by ewaltman** [gumlet/php-image-resize#72]
See https://eventviva.github.io/php-image-resize/class-Eventviva.ImageResize.html#_crop

optional params $postion and $allow_enlarge should be switched.

**Comment by adityapatadia** [comment]
Things are fine in code: https://github.com/eventviva/php-image-resize/blob/master/lib/ImageResize.php#L380

I don't know why it went wrong in docs. I will look into it when I get time. If you want, you can generate docs again and create PR against gh-pages branch.

**Comment by adityapatadia** [comment]
This is fixed.
